#!/bin/bash     

# Test for issuegen's basic functionality

set -xeuo pipefail

. ${KOLA_EXT_DATA}/test-util.sh

# Check that `console-login-helper-messages-issuegen.service` is enabled.
systemctl is-enabled ${PKG_NAME}-issuegen.service

# Check that `console-login-helper-messages-issuegen.path` is enabled.
systemctl is-enabled ${PKG_NAME}-issuegen.path

# Check that `console-login-helper-messages-gensnippet-ssh-keys.service` is enabled.
systemctl is-enabled ${PKG_NAME}-gensnippet-ssh-keys.service

# Check that the issue symlink was created.
# `issuegen` generates an issue at runtime, and places the generated file in 
# /run/issue.d/. To have agetty display this, a symlink from /etc/issue.d/ to 
# /run/issue.d/ is needed.
ls -l /etc/issue.d/40_${PKG_NAME}.issue > /tmp/symlink.txt
assert_file_has_content /tmp/symlink.txt '-> /run/console-login-helper-messages/40_console-login-helper-messages.issue'
ok symlink

# If SSH keys are present, check that SSH keys snippets were generated by 
# `gensnippet_ssh_keys` and successfully concatenated by `issuegen`.
if test -n "$(find /etc/ssh -name 'ssh_host_*_key' -print -quit)"; then
    assert_file_has_content /run/${PKG_NAME}/40_${PKG_NAME}.issue 'SSH host key:*'
    ok gensnippet_ssh_keys
fi

# Check that a new issue snippet is generated when a .issue file is dropped into 
# `/run/console-login-helper-messages/issue.d/`.
echo 'foo' > /run/${PKG_NAME}/issue.d/10_foo.issue
sleep 1
assert_file_has_content /run/${PKG_NAME}/40_${PKG_NAME}.issue 'foo'
ok ${PKG_NAME}-issuegen-runtime.path ${PKG_NAME}-issuegen-runtime.service

# Check that a new issue snippet is generated when a .issue file is dropped into
# `/etc/console-login-helper-messages/issue.d`.
# Files dropped under the /etc location above are expected to be unchanged 
# during system runtime and are read only during boot.
case "${AUTOPKGTEST_REBOOT_MARK:-}" in
    "") /tmp/autopkgtest-reboot mark1 ;;
    mark1) echo 'baz' > /etc/${PKG_NAME}/issue.d/10_baz.issue;
           sleep 1;
           assert_not_file_has_content /run/${PKG_NAME}/40_${PKG_NAME}.issue 'baz';
           /tmp/autopkgtest-reboot mark2 ;;
    mark2) assert_file_has_content /run/${PKG_NAME}/40_${PKG_NAME}.issue 'baz' ;;
esac
ok ${PKG_NAME}-issuegen.service
