#!/bin/bash

set -e

mkdir -p /run/coreos/issue.d

case "$1" in
    add)
        echo "${2}: \\4{${2}} \\6{${2}}" > "/run/coreos/issue.d/${2}.issue"
        ;;
    remove)
        rm -f "/run/coreos/issue.d/${2}.issue"
        ;;
esac

# Dynamically generated
echo -e "Test issue in /run/coreos/issue.d.\n" > /run/coreos/issue.d/test.issue

echo
echo 'This is \n (\s \m \r) \t' > /run/coreos/issue # TODO: put this in /usr/lib/coreos/issue.d
if [[ -d "/usr/lib/coreos/issue.d" ]]; then
  cat /usr/lib/coreos/issue.d/*.issue 2>/dev/null >> /run/issue || true
fi
if [[ -d "/run/coreos/motd.d" ]]; then
  cat /run/coreos/issue.d/*.issue 2>/dev/null >> /run/issue || true
fi
if [[ -d "/etc/coreos/motd.d" ]]; then
  cat /etc/coreos/issue.d/*.issue 2>/dev/null >> /run/issue || true
fi
echo
