#!/bin/bash

set -e

print_issue() {
    echo
    echo 'This is \n (\s \m \r) \t'
    for note in /run/coreos/issue.d/*; do
        [ -f "${note}" ] && cat "${note}"
    done
    echo
}

mkdir -p /run/issue.d

case "$1" in
    add)
        mkdir -p /run/coreos/issue.d
        echo "${2}: \\4{${2}} \\6{${2}}" > "/run/coreos/issue.d/${2}"
        ;;
    remove)
        rm -f "/run/coreos/issue.d/${2}"
        ;;
esac

# /run/issue is symlinked from /etc/issue
print_issue > /run/issue

echo "Test \"Public\" issue in /run/issue.d" > /run/issue.d/test-info.issue
