#!/bin/bash

set -e

mkdir -p /run/coreos/issue.d

rm -f /run/issue

case "$1" in
    add)
        echo "${2}: \\4{${2}} \\6{${2}}" > "/run/coreos/issue.d/${2}"
        ;;
    remove)
        rm -f "/run/coreos/issue.d/${2}"
        ;;
esac

echo
if [[ -d "/usr/lib/coreos/issue.d" ]]; then
  cat /usr/lib/coreos/issue.d/* 2>/dev/null >> /run/issue || true
fi
if [[ -d "/run/coreos/issue.d" ]]; then
  cat /run/coreos/issue.d/* 2>/dev/null >> /run/issue || true
fi
if [[ -d "/etc/coreos/issue.d" ]]; then
  cat /etc/coreos/issue.d/* 2>/dev/null >> /run/issue || true
fi
echo
