#!/bin/bash

set -e

GENERATED_MOTD="/run/fedora-user-messages.motd"
ANSI_LIGHT_RED='\033[1;31m'
ANSI_LIGHT_BLUE='\033[1;34m'
ANSI_NC='\033[0m'
SUBPOINT='  |->'

source /usr/lib/os-release

print_rpm_ostree_update_info() {
	echo -e "\n[ostree]"

	rpm-ostree status --json > /run/fedora-user-messages/rpm-ostree-status.json
	rpm-ostree upgrade --check > /run/fedora-user-messages/rpm-ostree-upgrade-check.out

	sec_advisories=$(cat /run/fedora-user-messages/rpm-ostree-upgrade-check.out | grep "SecAdvisories")
	pkg_diff=$(cat /run/fedora-user-messages/rpm-ostree-upgrade-check.out | grep "Diff")
	up_version=$(cat /run/fedora-user-messages/rpm-ostree-upgrade-check.out | grep "Version")
	up_version=$(awk '{ print $2 }' <<< "${up_version}")
	up_commit=$(cat /run/fedora-user-messages/rpm-ostree-upgrade-check.out | grep "Commit")
	up_commit=$(awk '{ print $2 }' <<< "${up_commit}")
	upgrade_deployment_pending_reboot=$(jq --arg commit "${up_commit}" '[.deployments[0].booted == false] and [.deployments[0]."base-checksum" | tostring == $commit]' /run/fedora-user-messages/rpm-ostree-status.json)
	up_commit=$(echo "${up_commit}" | awk '{ print substr($0,0,6) }')
	cur_version=$(jq '.deployments | map(select(.booted == true)) | .[]."version"' /run/fedora-user-messages/rpm-ostree-status.json)
	cur_version=$(sed -e 's/^"//' -e 's/"$//' <<< "${cur_version}")
	cur_commit=$(jq '.deployments | map(select(.booted == true)) | .[]."base-checksum"' /run/fedora-user-messages/rpm-ostree-status.json)
	cur_commit=$(sed -e 's/^"//' -e 's/"$//' <<< "${cur_commit}")
	cur_commit=$(echo "${cur_commit}" | awk '{ print substr($0,0,6) }')

	echo -e "current:   ${cur_version} (${cur_commit})"
	update_available_msg=$(echo -e "${ANSI_LIGHT_BLUE}available${ANSI_NC}: ${up_version} (${up_commit})")
	if [ "${upgrade_deployment_pending_reboot}" = "true" ]; then
		echo "${update_available_msg} - deployment pending next reboot"
	else
		echo "${update_available_msg}"
	fi


	if [ -n "${sec_advisories}" ]; then
		sec_advisories=$(awk '{$1=""; sub(" ", " "); print}' <<< "${sec_advisories}")
		sec_advisories=$(echo "${sec_advisories}" | sed -e "s/^[[:space:]]*//")
		echo -e "${SUBPOINT} ${ANSI_LIGHT_RED}advisories${ANSI_NC}: ${sec_advisories}"
	fi
	if [ -n "${pkg_diff}" ]; then
		pkg_diff=$(awk '{ $1="" ; sub(" ", " ") ; print }' <<< "${pkg_diff}")
		pkg_diff=$(echo "${pkg_diff}" | sed -e "s/^[[:space:]]*//")
		echo -e "${SUBPOINT} packages: ${pkg_diff}"
	fi
}

print_dnf_update_info() {
	echo -e "\n---- dnf"
	dnf -qC updateinfo > /run/fedora-user-messages/dnf-updateinfo.out
	cat /run/fedora-user-messages/dnf-updateinfo.out
}

mkdir -p /run/fedora-user-messages/motd.d

rm -f ${GENERATED_MOTD}

# Get updated system information and print it to the
# generated motd
echo -e "\e[${ANSI_COLOR}m${NAME}\e[39m (${VERSION})" > ${GENERATED_MOTD}

if [ -x "$(command -v rpm-ostree)" ]; then
	set +e
	print_rpm_ostree_update_info >> ${GENERATED_MOTD}
	set -e
fi
if [ -x "$(command -v dnf)" ]; then
	set +e
	print_dnf_update_info >> ${GENERATED_MOTD}
	set -e
fi

# Look in directories where additional messages are dropped, append
# to the generated motd.
if [[ -d "/usr/lib/fedora-user-messages/motd.d" ]]; then
	cat /usr/lib/fedora-user-messages/motd.d/* 2>/dev/null >> $GENERATED_MOTD || true
fi
if [[ -d "/run/fedora-user-messages/motd.d" ]]; then
	cat /run/fedora-user-messages/motd.d/* 2>/dev/null >> $GENERATED_MOTD || true
fi
if [[ -d "/etc/fedora-user-messages/motd.d" ]]; then
	cat /etc/fedora-user-messages/motd.d/* 2>/dev/null >> $GENERATED_MOTD || true
fi
