#!/usr/bin/bash
#
# Provide key fingerprints via issue.
#
# Copyright (c) 2020 Fedora CoreOS Authors. All rights reserved.
# Copyright (c) 2013 The CoreOS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
# Modified from the CoreOS repository: https://github.com/coreos/init/blob/master/scripts/sshd_keygen

set -e

. /usr/lib/console-login-helper-messages/libutil.sh
. /usr/lib/console-login-helper-messages/issuegen.defs

ssh_dir=/etc/ssh
# Ensure SSH directory is created and can be searched without error.
mkdir -p "${ssh_dir}"
outfile="${RUN_SNIPPETS}/21_ssh_host_keys.issue"

for key_file in $(find "${ssh_dir}" -name "ssh_host_*_key"); do
	ssh-keygen -l -f "${key_file}"
done \
    | awk '{print "SSH host key: " $2 " " $4}' \
    | write_via_tempfile "${outfile}"
