#!/usr/bin/bash
#
# Write distro release information to MOTD, in distro-specific color.
#
# Copyright (c) 2020 Fedora CoreOS Authors. All rights reserved.
# Copyright (c) 2014 The CoreOS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
# Modified from the CoreOS repository: https://github.com/coreos/init/blob/master/scripts/motdgen

set -e

. /usr/lib/console-login-helper-messages/libutil.sh
. /usr/lib/console-login-helper-messages/motdgen.defs

outfile="${RUN_SNIPPETS}/21_os_release.motd"

. /usr/lib/os-release
echo -e "\e[${ANSI_COLOR}m${PRETTY_NAME}\e[39m" \
    | write_via_tempfile "${outfile}"
