#!/bin/bash

# Get updated system information from package managers
# and generate a motd to display this at login.

set -e

PKG_NAME=console-login-helper-messages
MOTD_DIR_PUBLIC=motd.d
MOTD_DIR_PRIVATE=${PKG_NAME}/motd.d
GENERATED_MOTD=/run/${MOTD_DIR_PUBLIC}/${PKG_NAME}.motd

source /usr/lib/os-release

mkdir -p /run/${MOTD_DIR_PRIVATE}
mkdir -p /run/${MOTD_DIR_PUBLIC}
rm -f ${GENERATED_MOTD}
touch ${GENERATED_MOTD}

echo -e "\e[${ANSI_COLOR}m${NAME}\e[39m (${VERSION})" > ${GENERATED_MOTD}

echo >> ${GENERATED_MOTD}

if [[ -d "/etc/${MOTD_DIR_PRIVATE}" ]]; then
	cat /etc/${MOTD_DIR_PRIVATE}/* 2>/dev/null >> ${GENERATED_MOTD} || true
fi
if [[ -d "/run/${MOTD_DIR_PRIVATE}" ]]; then
	cat /run/${MOTD_DIR_PRIVATE}/* 2>/dev/null >> ${GENERATED_MOTD} || true
fi
if [[ -d "/usr/lib/${MOTD_DIR_PRIVATE}" ]]; then
	cat /usr/lib/${MOTD_DIR_PRIVATE}/* 2>/dev/null >> ${GENERATED_MOTD} || true
fi
